In [1]:
cd drive/MyDrive/github/HandGestureRecognition/

/content/drive/MyDrive/github/HandGestureRecognition


In [2]:
import pandas as pd
import numpy as np

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from torch.utils.data.sampler import SubsetRandomSampler
import torch.nn.functional as F
from torch import optim


In [3]:
LABEL_NAMES = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N',
          'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'del',
          'space']

In [4]:
class HGMDataset(Dataset):
  def __init__(self, csvpath):
    df = pd.read_csv(csvpath)
    df = df.sample(frac=1).reset_index(drop=True)       
    self.x = df.iloc[:,4:].values
    self.y = df['label'].values.reshape(-1,1)

  def __len__(self):
    return len(self.y)

  def __getitem__(self, idx):
    x_val  = torch.Tensor(self.x[idx])
    y_val  = torch.Tensor(self.y[idx])
    y_val  = y_val.type(torch.LongTensor)
    return { 'data': x_val,
            'target': y_val
            }

In [5]:
# df = pd.read_csv('asl_alphabet_train/labels.csv')
# df = df.sample(frac=1).reset_index(drop=True)       
# x = df.iloc[:,4:].values
# y = df['label'].values.reshape(-1,1)

In [6]:
HGM_data = HGMDataset('asl_alphabet_train/labels.csv')
#HGM_data.__getitem__(1)

In [7]:
## create training and validation split 
split = int(0.8 * len(HGM_data))
index_list = list(range(len(HGM_data)))
train_idx, valid_idx = index_list[:split], index_list[split:]

In [8]:
## create sampler objects using SubsetRandomSampler
tr_sampler = SubsetRandomSampler(train_idx)
val_sampler = SubsetRandomSampler(valid_idx)

In [9]:
## create iterator objects for train and valid datasets
trainloader = DataLoader(HGM_data, batch_size=64, sampler=tr_sampler)
validloader = DataLoader(HGM_data, batch_size=64, sampler=val_sampler)

In [10]:
class Model(nn.Module):
  def __init__(self):
    super().__init__()
    self.hidden1 = nn.Linear(42, 256)
    self.hidden2 = nn.Linear(256, 128)
    self.output = nn.Linear(128, 28)
  
  def forward(self, x):
    x = self.hidden1(x)
    x = F.relu(x)
    x = self.hidden2(x)
    x = F.relu(x)
    x = self.output(x)
    return x

In [11]:
model = Model()

In [12]:
model.load_state_dict(torch.load('landmark_model_100.pth'))

<All keys matched successfully>

In [ ]:
loss_function = nn.CrossEntropyLoss()
optimizer = optim.SGD(model.parameters(), lr=0.01, weight_decay= 1e-6, momentum = 0.9, nesterov = True)

In [ ]:
epochs = 100

for epoch in range(1, epochs+1): ## run the model for 100 epochs
  train_loss, valid_loss = [], []

  ## training part 
  model.train()

  for _, batch in enumerate(trainloader):
      
    data, target = batch['data'], batch['target']

    optimizer.zero_grad()

    ## 1. forward propagation
    output = model(data)

    ## 2. loss calculation
    loss = loss_function(output, target.squeeze(1))

    ## 3. backward propagation
    loss.backward()

    ## 4. weight optimization
    optimizer.step()

    train_loss.append(loss.item())
      
  ## evaluation part 
  model.eval()

  for _, batch in enumerate(validloader):

    data, target = batch['data'], batch['target']
    output = model(data)
    loss = loss_function(output, target.squeeze(1))
    valid_loss.append(loss.item())

  print ("Epoch:", epoch, "Training Loss: ", np.mean(train_loss), "Valid Loss: ", np.mean(valid_loss))


torch.save(model.state_dict(), f'landmark_model_{epochs}.pth')

Epoch: 1 Training Loss:  2.318478153518519 Valid Loss:  1.2544008037623238
Epoch: 2 Training Loss:  1.0001676783273354 Valid Loss:  0.7941928416490555
Epoch: 3 Training Loss:  0.6888530558980672 Valid Loss:  0.5962259871118208
Epoch: 4 Training Loss:  0.5529661241666054 Valid Loss:  0.525073784151498
Epoch: 5 Training Loss:  0.4867507097116262 Valid Loss:  0.46909551226040896
Epoch: 6 Training Loss:  0.44313140903602305 Valid Loss:  0.43040452888783287
Epoch: 7 Training Loss:  0.40904973792379234 Valid Loss:  0.40509174492429284
Epoch: 8 Training Loss:  0.38294233472957373 Valid Loss:  0.37793362973367467
Epoch: 9 Training Loss:  0.36055077380530953 Valid Loss:  0.3591895947999814
Epoch: 10 Training Loss:  0.341571423508073 Valid Loss:  0.3498428413534866
Epoch: 11 Training Loss:  0.325778055342689 Valid Loss:  0.3299587445004898
Epoch: 12 Training Loss:  0.31177483567182296 Valid Loss:  0.31511546822593495
Epoch: 13 Training Loss:  0.2998406714416359 Valid Loss:  0.30804373201201946
E

In [13]:
## dataloader for validation dataset 
dataiter = iter(validloader)
batch = dataiter.next()
data, labels = batch['data'], batch['target']
output = model(data)

_, preds_tensor = torch.max(output, 1)
preds = np.squeeze(preds_tensor.numpy())

print ("Actual:", labels.numpy().reshape(-1)[:10])
print ("Predicted:", preds[:10])

print(preds[:10] == labels.numpy().reshape(-1)[:10])

Actual: [ 8 25 19  9 24 25 18 20 25  2]
Predicted: [ 8 25 19  9 24 25 18 20 25  2]
[ True  True  True  True  True  True  True  True  True  True]


In [14]:
df = pd.read_csv('asl_alphabet_train/labels.csv')
df = df.sample(frac=1).reset_index(drop=True)       
x = df.iloc[:,4:].values
y = df['label'].values.reshape(-1,1)

In [15]:
x[1]

array([ 0.        ,  0.        ,  0.05786228, -0.06654346,  0.08304906,
       -0.14307708,  0.03804433, -0.19017434, -0.02180761, -0.21233875,
        0.05042607, -0.25779331,  0.03899133, -0.35060331,  0.02406031,
       -0.4007701 ,  0.00922436, -0.44758731, -0.00900739, -0.23962307,
       -0.01581275, -0.34495968, -0.01314265, -0.39164561, -0.00930548,
       -0.42453092, -0.06065243, -0.19943136, -0.0396719 , -0.21733195,
       -0.01066726, -0.16074717, -0.00620383, -0.14255244, -0.1006099 ,
       -0.14959776, -0.0787648 , -0.17250925, -0.04910809, -0.1371786 ,
       -0.04196107, -0.11914754])

In [22]:
output = model(torch.tensor(x[1]).type(torch.FloatTensor))
output 

tensor([ -7.0216,   6.0504, -12.7404,   8.0520,  -5.4963, -13.0640,   2.1838,
          8.2303,   4.5476,   2.6291,   8.7274,  -3.2178,  -0.3508,   9.9614,
        -13.8822,  -2.9866, -18.4252,  16.3872,   4.8337, -10.5987,  18.4459,
         10.7970,   8.6792,   5.0900, -14.3952, -13.2475,  -0.6711,  -3.9275],
       grad_fn=<AddBackward0>)

In [27]:
np.argmax(output.detach().numpy())

20

In [28]:
y[1]

array([20])